### ISSUE TITLE
Publish on FDroid

### ISSUE THREAD

**Issue by Wjxfi** [NightDreamGames/Graded#1]

**Comment by Poussinou** [comment]
@Wjxfi Currently, the app is available trough a F-Droid client via the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid/). The app is [here](https://apt.izzysoft.de/fdroid/index/apk/com.NightDreamGames.Grade.ly).

@FauconSpartiate You can start the process of adding your app to F-Droid by opening a Request For Packaging [here](https://gitlab.com/fdroid/rfp). I did a quick check, and I don't see any proprietary blob here, so it should be easy.

**Comment by FauconSpartiate** [comment]
The advancement of the release is tracked on this issue: https://gitlab.com/fdroid/rfp/-/issues/2390

**Comment by FauconSpartiate** [comment]
Graded is now available [on F-Droid](https://f-droid.org/en/packages/com.NightDreamGames.Grade.ly/) and the links have been added in the README in 55a9051

**Comment by IzzySoft** [comment]
@FauconSpartiate I see the Readme now has both badges, F-Droid's and mine. I take it that means you want to keep your app with my repo? Can be done, but as it's not set up as reproducible build with F-Droid this might cause some confusion (as cross-updates are not possible), so I thought to better ask about your plans.

**Comment by FauconSpartiate** [comment]
If there's any issue with that I'll prefer to remove it from your repo then, I'll remove the badge later 👍

**Comment by FauconSpartiate** [comment]
@IzzySoft I removed the badge from the README, I guess you can remove it from your repo. 
If we ever get reproducible builds working with Flutter, I guess we could put it back up again.

**Comment by IzzySoft** [comment]
Thanks – and yes, that can be done of course. Just keep in mind that reproducible builds should be set up from the start; switching to them is not as easy (signature change => re-install needed).
