### ISSUE TITLE
Can't change rating system 

### ISSUE THREAD

**Issue by NobodyForNothing** [NightDreamGames/Graded#11]
When clicking on the change rating system settings tile, a broken Dialog appears.

version: 2.5.0

![Screenshot_2023-11-14-19-15-00-992_com.NightDreamGames.Grade.ly.jpg](https://github.com/NightDreamGames/Graded/assets/82763757/6dd91600-255d-4686-8ce3-4ee1d525100c)

**Comment by FauconSpartiate** [comment]
Thank you, slight oversight from last version 👍🏻
