### ISSUE TITLE
Add button sometimes adds to every trimester 

### ISSUE THREAD

**Issue by NobodyForNothing** [NightDreamGames/Graded#12]
Steps:
1. start with new app install (default settings, other shool system)
2. add subject (through settings after initial dialog)
3. add value 

Result: All trimesters seem to share the same data source

version: 2.5.0

**Comment by FauconSpartiate** [comment]
Nice catch 👍🏻

**Comment by FauconSpartiate** [comment]
@NobodyForNothing A workaround in the meantime until I release this fix is to close and reopen the app after adding the subject.
They won't be linked between terms anymore after the restart.
