### ISSUE TITLE
Keep subjects from previous year

### ISSUE THREAD

**Issue by tippfehlr** [NightDreamGames/Graded#14]
Currently, when creating a new year, all subjects have to be created manually again (when using “other school system”).

It would be nice to be able to keep or import them. 

PS: Thanks for adding year management. The font also looks great!

**Comment by FauconSpartiate** [comment]
I could add a "Copy" option in the menu when you tap on a year.

**Comment by tippfehlr** [comment]
That would work, although a Dialog which asks whether to copy the subjects from the previous year is a little more user-friendly imo.

And the grades shouldn't be kept of course

**Comment by FauconSpartiate** [comment]
Added in a5dd608

I added a popup when creating a new year and going on the subject creation page.

![image](https://github.com/NightDreamGames/Graded/assets/49079695/2d2d3792-39c1-4f32-897e-7bd3bba7466e)
