### ISSUE TITLE
Can't edit years.

### ISSUE THREAD

**Issue by DOC2212** [NightDreamGames/Graded#15]
When i goto Manage Years in Android App, I can't edit the year, such as changing the name. I've cleared the cache, data and even uninstalled the app.
Nothing works 
![Screenshot_20231222_211827](https://github.com/NightDreamGames/Graded/assets/154636322/c72861bb-d42d-4c66-9539-e02d12c2b41d)

**Comment by FauconSpartiate** [comment]
Same underlying problem as #11, just need to apply the fix to this part too.
First thing I do tomorrow.
