### ISSUE TITLE
Allow adding .5 bonuses

### ISSUE THREAD

**Issue by Murilogs1910** [NightDreamGames/Graded#18]
At my school, grades range from 0 to 10, with decimals, and bonuses are usually of 1 or 0.5. In the app, however, I can only increment the bonus by 1.

Alternative solution: Remove the limit of 9 to bonuses. Without that limit, I could just convert the grades from the 10.0 system to 100 in the app, and add 5 or 10 as bonus.

**Comment by FauconSpartiate** [comment]
Already fixed on main branch, bonus has been moved to its own dialog and allows any input.
Will be released in next version.

**Comment by FauconSpartiate** [comment]
Released in 2.6.5
