### ISSUE TITLE
Limit the average at the Rating System's limit

### ISSUE THREAD

**Issue by Murilogs1910** [NightDreamGames/Graded#19]
Say the limit is 10. If, in 3 tests I scored 10, 9.4, and 10, my average would be of 9.8. However, I have 1 point as bonus. Adding it there makes the average as 10.8, which is past the limit of 10.

 The average should be capped at the maximum score the rating system allows. So, in the example provided, even with a 1 point bonus, the average should only get to 10, not 10.8.

**Comment by FauconSpartiate** [comment]
Good point, never considered it.

**Comment by FauconSpartiate** [comment]
Released in `2.6.5`
