### ISSUE TITLE
Coefficients et valeurs maximales.

### ISSUE THREAD

**Issue by Herostar873** [NightDreamGames/Graded#22]
J'ai vu que quand je mets une note avec une valeur maximale "Max." différentes de la valeur dont la moyenne est calculée. Par exemple, la moyenne est calculée sur 60 et je mets une note sur 30 coefficient 1 ET une autre note sur 60 coefficient 1. La moyenne me calcule la note sur 60 coef 1 certes mais la note sur 30 passe automatiquement coef 0,5. J'ai remarqué une division ou une multiplication automatique en fonction de la valeur maximale. Et je voudrais que l'ont puisse désactiver ça ou alors le laisser si on veut.

**Comment by FauconSpartiate** [comment]
C'est une idée à investiguer.

Le même résultat peut être obtenu en mettant la note sur 30 à coefficient 2.

Dans quel contexte est-ce que cette option serait utile? En géneral les devoirs de sur 30 points compent aussi juste pour la moitié dans la moyenne...
