### ISSUE TITLE
Bad average if...

### ISSUE THREAD

**Issue by Herostar873** [NightDreamGames/Graded#23]
I'd like there to be a feature about coefficients when the maximum value is different from the one chosen. For example, the marking system is based on 60, so I set 30/60 weight : 1 and 6/30 weight : 1 too. The average should be 21/60. But there is an automatic division of the coefficient. Would it be possible to deactivate automatic multiplication or division when the maximum values are not the same between assignments?

**Comment by ConEstArthur** [comment]
Need the same.
Thanks for reporting

**Comment by FauconSpartiate** [comment]
@ConEstArthur @Herostar873 
I just added this functionality in b75238057155d8fcb057afd4f6f7768b33f0b606, I'll publish it in the next release.

**Comment by FauconSpartiate** [comment]
So now there will be an option in the settings that's called "Scale up tests", which gives the calculation system you are looking for when enabled.

**Comment by FauconSpartiate** [comment]
Released in 2.7.2

**Comment by ConEstArthur** [comment]
> Released in `2.7.2`

Working really well so far.
Thanks a lot ☺️
