### ISSUE TITLE
Other school systems (Germany / Hamburg)

### ISSUE THREAD

**Issue by tippfehlr** [NightDreamGames/Graded#9]
Would it be possible to add other countries? Where would I need to start when adding another school system?

**Comment by FauconSpartiate** [comment]
Most of the work lies in actually having the data in an usable format, like json or csv.
This means seeing all the available classes with all their respective subjects, coefficients and other data.
You'll have to find the data on the government or school websites, then transpose it to json, which can take more or less time, depending if the data is easily scrapable or not.
You can take a look at this folder, where the data from the Luxembourgish system is:
https://github.com/NightDreamGames/Graded/tree/master/assets%2Fclass_data

**Comment by FauconSpartiate** [comment]
I'll then have to work at the UI to make everything make sense and prevent cluttering everything up, but this comes after the data has been defined.

**Comment by tippfehlr** [comment]
In Germany we don’t have set classes, so users will still need to set them themselves.
What we have is a different grading system where the grades are 1+ > 1 > 1- > 2+ > 2 > 2- > 3+ > 3 > 3- > 4+ > 4 > 4- > 5+ > 5 > 5- > 6. I don’t need them, but if you have time to burn that could be implemented. (although there are some states where 1+ = 0.7 and 2- = 2.3 and others where 1+ = 0.75 and 2- = 2.25 so that would also need to be selectable)

**Comment by FauconSpartiate** [comment]
Okay, this will be something new to implement, like having mutliple different grading systems.

Is this scale linear? Meaning that for example a grade from 0-100 can be linearly translated to the german system, where 100 is 1+ and 0 is 6?

**Comment by tippfehlr** [comment]
1 to 6 are linear, the + and - factors are not, I think. To calculate an average, the decimal values of grades are used (0.7 to 6)

**Comment by FauconSpartiate** [comment]
I'll dig into this, thank you

**Comment by tippfehlr** [comment]
I am closing this since I didn't do it in almost a year and it would probably be outdated pretty quickly, and it would only apply to Hamburg (every state in Germany has its own school system). Thanks for the consideration, it works pretty well right now anyways.
